"""Correlation is generated by the server and propagated across transports/services."""

from contextvars import ContextVar
from uuid import UUID, uuid4

request_context: ContextVar[UUID | None] = ContextVar("smm_request_id", default=None)


def request_id() -> UUID:
    return request_context.get() or uuid4()
